# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jeff & Geo
tagline:          'A Jekyll theme'
description:      'Bem-vindos ao nosso site. Aqui vocês vão encontrar todas as informações sobre nós e nosso casamento.'
url:              http://jeff-geo.campos.nom.br
baseurl:          /

author:
  name:           'Jefferson Campos'
  url:            https://jeffersoncampos.eti.br

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/foguinhoperuca/jeff-geo.campos.nom.br
